trade:
  server:
    server_name: "[SERVER]"
  GUI:
    GUI_name: "§bTRADE"
  msg:
    info1: "Demande de trade envoyé à $ !"
    info2: "Vous avez (1) nouvelle demande de trade par $"
    info3: "La demande de trade par $ à été accepté !"
    info4: "La demande de trade par $ à été refusé !"
    info5: "Vous avez accepté la demande de trade"
    info6: "Vous avez refusé la demande de trade"
    error1: "Tu ne peux pas trade avec toi même"
    error2: "Délais de demande de trade dépassé"
    error3: "Le joueur n'existe pas ou n'est pas connecté !"
    error4: "Tu n'as pas de demande en cours !"